server:
  port: 8080

spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
  data:
    mongodb:
      uri: mongodb+srv://thilina:thilina@smartcampus.xakxcat.mongodb.net/smart_campus_db?retryWrites=true&w=majority&appName=smartCampus

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 769470730880-ntp2dd63cmtb4sqmd43r85tplfqb2ehu.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
              - openid
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"

app:
  jwt:
    secret: SmartCampusHub2026SecretKeyForJWTTokenGenerationAndValidation256Bit!!
    expiration-ms: 86400000  # 24 hours
  cors:
    allowed-origins: http://localhost:5173
  google:
    client-id: 769470730880-ntp2dd63cmtb4sqmd43r85tplfqb2ehu.apps.googleusercontent.com
